// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vogguouoilhyujedsmsi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZvZ2d1b3VvaWxoeXVqZWRzbXNpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIwMjA5MDYsImV4cCI6MjA2NzU5NjkwNn0.ufDVo8Q9v4WGgvxPu9n-XV7f8y-d8xRtVSnxDTy-Saw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});